name: Backup Slack

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup | Cache Stack
        id: cache-stack
        uses: actions/cache@v4.2.0
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('**/package.yaml') }}-${{ hashFiles('**/stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-stack-
      - name: Setup | Stack and GHC
        uses: haskell-actions/setup@v2.7.6
        with:
          ghc-version: 8.10.4 # stack.yamlのresolverに合わせて更新してください
          enable-stack: true
          stack-version: latest
      - name: Setup | Pull objects from R2
        uses: ./.github/actions/rclone
        with:
          config: ${{ secrets.RCLONE_CONFIG }}
          args: "sync r2:suzuka-kosen-festa-slack-archive ./docs"
      - name: Setup | chown to runner
        run: sudo chown -R runner:docker ./docs
      - name: Run | Archive Slack
        run: stack build --exec 'slack-archive save'
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
      - name: Run | Upload Archive
        uses: ./.github/actions/rclone
        with:
          config: ${{ secrets.RCLONE_CONFIG }}
          args: "sync ./docs r2:suzuka-kosen-festa-slack-archive"
